name: Deploy .NET Worker to Linode

on:
  push:
    branches:
      - main
  workflow_dispatch: # <--- ADD THIS LINE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Specify the .NET SDK version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish src/Worker/eBird.Ingestor.Worker.csproj --configuration Release --no-build --output publish

    - name: Rename appsettings.template.json
      run: mv publish/appsettings.template.json publish/appsettings.json

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: worker-app
        path: publish

  deploy:
    needs: build # This job depends on the 'build' job completing successfully
    runs-on: ubuntu-latest

    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v4
      with:
        name: worker-app
        path: ./app

    - name: Copy application to Linode
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        source: "app/."
        target: "/APPS/ebird-ingestor"

    - name: Restart service on Linode
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        key: ${{ secrets.LINODE_SSH_KEY }}
        script: |
          DEPLOY_PATH="/APPS/ebird-ingestor"
          # Set permissions
          sudo chmod -R 755 $DEPLOY_PATH
          # Restart the service
          sudo systemctl restart ebird-ingestor.service
          sudo systemctl enable ebird-ingestor.service